export const TOKENS = {
  AuthRemoteDS: Symbol("AuthRemoteDS"),
  AuthRepo: Symbol("AuthRepo"),
  LoginUC: Symbol("LoginUC"),
  SignupUC: Symbol("SignupUC"),
  LogoutUC: Symbol("LogoutUC"),
  GetCurrentUserUC: Symbol("GetCurrentUserUC"),
  GetUserIdByEmailUC: Symbol("GetUserIdByEmailUC"),
  ProductRemoteDS: Symbol("ProductRemoteDS"),
  ProductRepo: Symbol("ProductRepo"),
  AddProductUC: Symbol("AddProductUC"),
  UpdateProductUC: Symbol("UpdateProductUC"),
  DeleteProductUC: Symbol("DeleteProductUC"),
  GetProductsUC: Symbol("GetProductsUC"),
  GetProductByIdUC: Symbol("GetProductByIdUC"),
  // Course tokens
  CourseRemoteDS: Symbol("CourseRemoteDS"),
  CourseRepo: Symbol("CourseRepo"),
  CreateCourseUC: Symbol("CreateCourseUC"),
  GetAllCoursesUC: Symbol("GetAllCoursesUC"),
  GetCourseByIdUC: Symbol("GetCourseByIdUC"),
  JoinCourseUC: Symbol("JoinCourseUC"),
  // Category tokens
  CategoryRemoteDS: Symbol("CategoryRemoteDS"),
  CategoryRepo: Symbol("CategoryRepo"),
  GetCategoriesUC: Symbol("GetCategoriesUC"),
  AddCategoryUC: Symbol("AddCategoryUC"),
  UpdateCategoryUC: Symbol("UpdateCategoryUC"),
  DeleteCategoryUC: Symbol("DeleteCategoryUC"),
  // Group tokens
  GroupRemoteDS: Symbol("GroupRemoteDS"),
  GroupRepo: Symbol("GroupRepo"),
  GetGroupsByCategoryUC: Symbol("GetGroupsByCategoryUC"),
  CreateGroupsForCategoryUC: Symbol("CreateGroupsForCategoryUC"),
  AssignStudentToGroupUC: Symbol("AssignStudentToGroupUC"),
  MoveStudentToGroupUC: Symbol("MoveStudentToGroupUC"),
  FindStudentGroupUC: Symbol("FindStudentGroupUC"),
  JoinGroupUC: Symbol("JoinGroupUC"),
  // Activity tokens
  ActivityRemoteDS: Symbol("ActivityRemoteDS"),
  ActivityRepo: Symbol("ActivityRepo"),
  CreateActivityUC: Symbol("CreateActivityUC"),
  GetActivitiesByCategoryUC: Symbol("GetActivitiesByCategoryUC"),
  GetActivityByIdUC: Symbol("GetActivityByIdUC"),
  UpdateActivityUC: Symbol("UpdateActivityUC"),
  DeleteActivityUC: Symbol("DeleteActivityUC"),
  // Evaluation tokens
  EvaluationRemoteDS: Symbol("EvaluationRemoteDS"),
  EvaluationRepo: Symbol("EvaluationRepo"),
  CreateEvaluationUC: Symbol("CreateEvaluationUC"),
  GetEvaluationsByActivityUC: Symbol("GetEvaluationsByActivityUC"),
  UpdateEvaluationUC: Symbol("UpdateEvaluationUC"),
  CheckEvaluationEligibilityUC: Symbol("CheckEvaluationEligibilityUC"),
} as const;
